FROM serversideup/php:8.4-fpm-nginx-alpine

USER root

WORKDIR /var/www/html

RUN apk add --no-cache \
    bash \
    curl \
    git \
    nodejs \
    npm \
    su-exec

COPY --chown=www-data:www-data . /var/www/html
COPY --chmod=755 docker/development/entrypoint-local.sh /usr/local/bin/entrypoint-local.sh

RUN chown -R www-data:www-data /var/www/html

EXPOSE 8000

ENTRYPOINT ["/usr/local/bin/entrypoint-local.sh"]
