#!/usr/bin/with-contenv bash
set -euo pipefail

POSTGRES_DATA_DIR="/var/lib/postgresql/data"

if [ ! -s "${POSTGRES_DATA_DIR}/PG_VERSION" ]; then
    su -s /bin/sh postgres -c "initdb -D ${POSTGRES_DATA_DIR}"

    su -s /bin/sh postgres -c "pg_ctl -D ${POSTGRES_DATA_DIR} -o \"-c listen_addresses='*'\" -w start"

    su -s /bin/sh postgres -c "psql -v ON_ERROR_STOP=1 --username postgres --dbname postgres <<SQL
DO \$\$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${DB_USERNAME}') THEN
        CREATE ROLE ${DB_USERNAME} LOGIN PASSWORD '${DB_PASSWORD}';
    END IF;
END
\$\$;
SQL"

    su -s /bin/sh postgres -c "psql -v ON_ERROR_STOP=1 --username postgres --dbname postgres <<SQL
SELECT 'CREATE DATABASE ${DB_DATABASE} OWNER ${DB_USERNAME}'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${DB_DATABASE}')\gexec
SQL"

    su -s /bin/sh postgres -c "pg_ctl -D ${POSTGRES_DATA_DIR} -m fast -w stop"
fi

exec su -s /bin/sh postgres -c "exec postgres -D ${POSTGRES_DATA_DIR} -c listen_addresses='*'"
